///////////////////////////////////////////////////////////
//  Alumno.cs
//  Implementation of the Class Alumno
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 10:58:57 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Entidades;
namespace Entidades {
	public class Alumno {

		private string _nombre;
		private string _apellido;
		private string _legajo;
		public Desempenio m_Desempenio;

		public Alumno(){

		}

		~Alumno(){

		}

		public virtual void Dispose(){

		}

		public void Nombre{
			get;
			set;
		}

		public void Apellido{
			get;
			set;
		}

		public void Legajo{
			get;
			set;
		}

	}//end Alumno

}//end namespace Entidades