///////////////////////////////////////////////////////////
//  Desempenio.cs
//  Implementation of the Class Desempenio
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 10:58:57 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Entidades;
namespace Entidades {
	public class Desempenio {

		private float _promedio;
		public Materia m_Materia;

		public Desempenio(){

		}

		~Desempenio(){

		}

		public virtual void Dispose(){

		}

		public void Promedio{
			get;
			set;
		}

	}//end Desempenio

}//end namespace Entidades