///////////////////////////////////////////////////////////
//  GestorDesempenio.cs
//  Implementation of the Class GestorDesempenio
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 10:59:43 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Entidades;
namespace Controlador {
	public class GestorDesempenio {
		
		private Alumno _alumno = new Alumno();
		
		public GestorDesempenio(){

		}

		~GestorDesempenio(){

		}

		public virtual void Dispose(){

		}

		public void GuardarAlumno(object o)
		{
			_alumno = (Alumno) o;
		}

		public Alumno ObtenerAlumno(){

			return _alumno;
		}

		public void GuardarMateria(object o){

		}

		public Materia ObtenerMateria(){

			return null;
		}

		public Desempenio ObtenerDesempenio(){

			return null;
		}

		public void ValidarAlumno(){

		}

		public void ValidarMateria(){

		}

	}//end GestorDesempenio

}//end namespace Controlador