///////////////////////////////////////////////////////////
//  FormularioAlumno.cs
//  Implementation of the Class FormularioAlumno
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:33 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Interfaz;
using Controlador;
namespace Interfaz {
	public class FormularioAlumno : Formulario {

		public FormularioAlumno(){

		}

		~FormularioAlumno(){

		}

		public override void Dispose(){

		}

		public override void IngresarCampos(){

		}

	}//end FormularioAlumno

}//end namespace Interfaz