///////////////////////////////////////////////////////////
//  Formulario.cs
//  Implementation of the Class Formulario
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:33 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Interfaz;
namespace Interfaz {
	public class Formulario : IFormulario {

		public Formulario(){

		}

		~Formulario(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Titulo"></param>
		public void MostrarTitulo(string Titulo){

		}

		/// 
		/// <param name="objeto"></param>
		public void MostrarCampos(Object objeto){

		}

		public void IngresarCampos(){

		}

	}//end Formulario

}//end namespace Interfaz