///////////////////////////////////////////////////////////
//  IFormulario.cs
//  Implementation of the Class IFormulario
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:33 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




namespace Interfaz {
	public class IFormulario {

		public IFormulario(){

		}

		~IFormulario(){

		}

		public virtual void Dispose(){

		}

		/// 
		/// <param name="Titulo"></param>
		public void MostrarTitulo(string Titulo){

		}

		/// 
		/// <param name="objeto"></param>
		public void MostrarCampos(Object objeto){

		}

	}//end IFormulario

}//end namespace Interfaz