///////////////////////////////////////////////////////////
//  IMenu.cs
//  Implementation of the Interface IMenu
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:33 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




namespace Interfaz {
	public interface IMenu {

		void MostrarTitulo();

		void MostrarOpciones();

		void VolverMenuAnterior();
	}//end IMenu

}//end namespace Interfaz