///////////////////////////////////////////////////////////
//  Menu.cs
//  Implementation of the Class Menu
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:34 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Interfaz;
namespace Interfaz {
	public class Menu : IMenu {

		public Menu(){

		}

		~Menu(){

		}

		public virtual void Dispose(){

		}

		public void MostrarTitulo(){

		}

		public void MostrarOpciones(){

		}

		public void VolverMenuAnterior(){

		}

	}//end Menu

}//end namespace Interfaz