///////////////////////////////////////////////////////////
//  Menu2.cs
//  Implementation of the Class Menu2
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:34 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Interfaz;
namespace Interfaz {
	public class Menu2 : Menu {

		public Formulario m_Formulario;

		public Menu2(){

		}

		~Menu2(){

		}

		public override void Dispose(){

		}

		public void MostrarTitulo(){

		}

		public void MostrarOpciones(){

		}

		public void VolverMenuAnterior(){

		}

	}//end Menu2

}//end namespace Interfaz