///////////////////////////////////////////////////////////
//  Menu1.cs
//  Implementation of the Class Menu1
//  Generated by Enterprise Architect
//  Created on:      25-oct-2011 11:00:34 a.m.
//  Original author: Victor
///////////////////////////////////////////////////////////




using Interfaz;
namespace Interfaz {
	public class Menu1 : Menu {

		public Formulario m_Formulario;

		public Menu1(){

		}

		~Menu1(){

		}

		public override void Dispose(){

		}

		public void MostrarTitulo(){

		}

		public void MostrarOpciones(){

		}

		public void VolverMenuAnterior(){

		}

	}//end Menu1

}//end namespace Interfaz